controllers-films-users
Daniil-Gorobets/java-filmorate pull request #1
Opened 2022-07-23 21:37 UTC by Daniil-Gorobets

Добавлено:
 - молели данных Film и User;
 - REST-контроллеры FilmController  и UserController;
 - валидация данных в запросе на добавление нового фильма или пользователя;
 - логирование;
 - тесты.

2022-07-25 12:59 UTC, Fleaman777 requested changes

2022-07-25 12:59 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.error("ValidationException: " + exceptionMessage);
для добавления информации в лог можно использовать встроенный в логгер форматтер через фигурные скобки: 
log.error("ValidationException: {}",  exceptionMessage);

применимо и в юзер контроллере

2022-07-25 12:59 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        }
весь этот if тоже можно было бы вынести в валидационный метод

2022-07-25 12:59 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.error("ValidationException: " + exceptionMessage);
можно было бы отдельно не создавать месседж для логгера, а сразу писать это сообщение в лог

применимо и в юзер контроллере

2022-07-25 12:59 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        user.setId(idCounter);
если сразу сделать user.setId(++idCounter); то на 1 строчку можно сократить код :)

2022-07-25 12:59 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +}
в целом, не обязательно создавать на этот класс тест, 
т.к. все основные тесты будут писаться в др классах

2022-07-25 12:59 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    }
хорошее использование метода с аннотацией @BeforeEach

2022-07-25 12:59 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                + "This text is longer than 200 chars. This text is longer than 200 chars.");
т.к. не сильно важно что находится в описании, главное что оно не проходит валидацию,
поэтому длинное описание можно вынести в константу, что бы код чуть легче всопринимася

2022-07-25 12:59 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    protected void validateUser(User user) {
хорошо что валидацию вынес в отдельный метод,

но более правильный подход тогда, когда контроллер только принимает запросы и отдает респонсы, а всю остальную логику выполняют другие классы(сервисы)

это не считается ошибкой,
выносить этот метод в отдельный класс или нет остается за тобой :)

аналагично и в фильм контроллере

2022-07-25 12:59 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +}
В enterprise приложениях на java, особенно написанных на Spring, в ....ControllerTest обычно тестируется api - на контроллер приходят определенные запросы(это делается специальной сущностью, а не просто вызывается эндпоинт метод), приложение полностью все отрабатывает, и затем отвечает определенным кодом и response body, которые и проверяются - такие тесты называются интеграционными. им ты научишься  чуть позже

Валидацию хорошо тестировать в обычных юнит тестах. Как раз, это будет проще сделать, если ее вынести в отдельный класс в отдельной директории.

этот комментарий тоже больше для информации,
если вдруг решишь часть валидации вынести в отдельный класс, можешь частично реализовать этот подход

2022-07-26 14:14 UTC, Fleaman777 requested changes

2022-07-26 14:14 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +package ru.yandex.practicum.filmorate.validator;public class FilmValidator {
немного поехало форматирование 

если код пишешь в IntellijIdea, то можешь использовать сочетание клавиш ctrl+alt+L, что бы выравнивать форматирование

2022-07-26 14:14 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/validator/FilmValidatorTest.java
> +class FilmValidatorTest {
тут между строками должна быть пустая строка

2022-07-26 17:55 UTC, Daniil-Gorobets commented
Странно, почему-то в прошлый раз запушилась только малая часть изменений. Последний (4-й) коммит проверил, вроде с исходником сходится

2022-07-27 08:45 UTC, Fleaman777 requested changes

2022-07-27 08:45 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +public class FilmValidator {
Здорово. Молодец, что решил пойчти немного по долгому пути, но по более правильному и вынес валидацию в отдельный класс

2022-07-27 11:09 UTC, merged