Develop
Daniil-Gorobets/java-filmorate pull request #27
Opened 2022-08-22 09:38 UTC by Daniil-Gorobets

Добавлен функционал:
 - Отзывы
 - Вывод самых популярных фильмов по жанру и годам
 - Лента событий
 - Общие фильмы
 - Поиск
 - Удаление фильмов и пользователей
 - Добавление режиссеров в фильм
 - Рекомендации

2022-08-23 10:01 UTC, Fleaman777 requested changes
Ребята привет.

Поздравляю вас с завершением такой масштабной работы. Вы большие молодцы.
Мне очень понравилась ваша работа, видно что проделан большой путь, и однозначно, небезрезультатный. Замечания есть, но их не много и они совсем некритичные.
Что мог бы отметить отдельно: здоровские запросы, составлены грамотно и оптимально, на достойном уровене. Логика в сервисах, тоже на отлично, вопросов практически не вызывает, так же как и контроллеры.
Так держать 💪🏼

2022-08-23 10:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    private final FilmStorage filmStorage;
контроллер не должен напрямую обращаться к репозиторию и стореджу, вся логика осуществляется через соответствующие методы сервисов

2022-08-23 10:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    int entityId;
поля должны быть private

2022-08-23 10:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            }
попробуйте foreach'и выше сделать через стрим, 
должно получится и компактнее и красивей :)

2022-08-23 10:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorRepository.java
> +        String sqlQuery2 = "INSERT into FILM_DIRECTORS (FILM_ID, DIRECTOR_ID) " +
для лучшего восприятия, заросы лучше делать в одном стиле 
вот этот больше всего удобен: 
ключевые слова SELECT, FROM и пр. в верхнем регистре, названия таблиц и столбцов в нижнем

2022-08-23 10:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            }
длинные методы ухудшают читаемость кода

поэтому логику внутри  if'ов хорошо было бы вынести в отдельные методы, так код будет легче восприниматься 

а так же, еще посмотреть, что можно было бы вынести в общие для всех методы

2022-08-23 10:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        }
эту логику можно сделать в стриме

2022-08-23 10:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        return films;
здесь тоже можно сделать через стрим

2022-08-23 10:01 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                        "select FILM_ID from LIKES where USER_ID = ?) group by FILM_ID order by c desc)";
запрос должен содержать не больше 1 подзапроса, 
если возникнут сложности с его переписыванием, наставник поможет :)

2022-08-26 20:32 UTC, Fleaman777 requested changes
Отличные исправления, молодцы!
Но есть немного моментов которые можно было бы поправить. Финиш близко! :)

2022-08-26 20:32 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +        return directors != null
Как ещё один вариант, пробрасывать из сервиса исключение, в контроллере его отлавливать и отдавать соответсвующий респонс.

переделывать не надо, но кому-то такой подход может показаться лучше

2022-08-26 20:32 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        }
Можно чуть проабдейтить эту логику 
Воспользоваться методом .foreach() а внутри метода использовать метод референс (:: - вот такая конструкция) на load….

2022-08-26 20:32 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +        }
Да и в целом вынести этоу логику в отдельный метод

2022-08-27 09:09 UTC, Fleaman777 approved these changes
Все отлично.
Можно еще раз однозначно сказать, вы крутые ! :)
Получено огромное количество бесценного опыта, который обязательно пригодится.
Удачи в дальнейшем обучении и в новой карьере

2022-08-27 11:01 UTC, golovkinen commented
@Fleaman777 Привет. Спасибо. Но наш pullrequest все ещё требует твой review для мерджа.

2022-08-27 13:51 UTC, merged